name: Build Verification

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-verify:
    name: "Build & Verify on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Build and verify
        shell: bash
        run: |
          ./build.sh --verify
